### ISSUE TITLE
Error: "Property 'namespace' not found on type 'Kubernetes.DotNet.Config.ContextData'."

### ISSUE THREAD

**Issue by ferpega** [masroorhasan/Kubernetes.DotNet#18]
Hello,
I am trying to follow your more basic example.  Getting configuration from .kube\config (on a Windows 10 OS).

But I always get this error:
"Property 'namespace' not found on type 'Kubernetes.DotNet.Config.ContextData'."

Anyway all my 'kubectl' commands run fine againts my selected/default namespace.

I think it is a problem of my own, but I cannot find it out how to avoid it on the startup guide.
Any idea?
Thanks.

**Comment by masroorhasan** [comment]
@ferpega good catch, yes this is a bug - looks like I missed adding `namespace` to context data: https://github.com/masroorhasan/Kubernetes.DotNet/blob/master/src/Kubernetes.DotNet/Config/KubeConfig.cs#L113

Its a simple fix, I could try to put up a PR today or feel free to add a patch also 😃.

**Comment by ferpega** [comment]
Thank you so much. 
:-) 

And, there is any possibility to indicate the complete path for config file?
I am thinking on having config file for machine wide instead of user.

Best regards and good job.

**Comment by masroorhasan** [comment]
@ferpega no problem at all! 

About your second point, the client configuration does support specifying custom paths to your kubeconfig file: https://github.com/masroorhasan/Kubernetes.DotNet/blob/master/src/Kubernetes.DotNet/Config/KubeConfigClientConfiguration.cs#L21

So, it would look something like this:
```
IKubernetesClient k8sClient = new KubeConfigClientConfiguration("your\\global\\path\\to\\kube\\config").CreateClient(AuthType.SSLAuth);
```
That should really be added to the documentation, i'll update the README in the same PR to make that clear. Thanks for catching that as well!
